### ISSUE TITLE
Demo script for mutator fails on custom code

### ISSUE THREAD

**Issue by dgrahn** [TestingResearchIllinois/srciror#5]
All,

I apologize for the title of this, I'm not sure how to be much more specific. In the demo directory, I replaced `max.c` with the following code. 

```c
#include <string.h>

int main(int argc, char *argv[]) {
  int copy_size;
  char src[10];
  char buf[10];

  memset(src, 'A', 10);
  src[10 - 1] = '\0';
  copy_size = 10;
  if (copy_size <= (int)(sizeof buf)) {
    memcpy(buf, src, copy_size);
  }

  return 0;
}
```

I have been able to run `./run-src-mutants.sh` with the example `max.c`, but now I'm getting the following output.

```
$ ./run-src-mutants.sh
rm -f max
/home/dangrahn/srciror/Demo/../PythonWrappers/mutationClang -O0 -o max /home/dangrahn/srciror/Demo/max.c
logging compile flags: -O0 -o max /home/dangrahn/srciror/Demo/max.c
THE CURRENT DIRECTORY IS: /home/dangrahn/srciror/Demo
THE ACTUAL COMMAND IS: /home/dangrahn/srciror/Demo/../SRCMutation/build/mutator /home/dangrahn/srciror/Demo/max.c -coverage_info=5,6,7,8,9,10,13 -- -O0 -o max /home/dangrahn/srciror/Demo/max.c -I/home/dangrahn/srciror/Demo/../llvm-build/Release+Asserts/lib/clang/3.8.0/include/
['/home/dangrahn/srciror/Demo/../SRCMutation/build/mutator', '/home/dangrahn/srciror/Demo/max.c', '-coverage_info=5,6,7,8,9,10,13', '--', '-O0', '-o', 'max', '/home/dangrahn/srciror/Demo/max.c', '-I/home/dangrahn/srciror/Demo/../llvm-build/Release+Asserts/lib/clang/3.8.0/include/']

Looking to compile the original: ['/home/dangrahn/srciror/Demo/../llvm-build/Release+Asserts/bin/clang', '-O0', '-o', 'max', '/home/dangrahn/srciror/Demo/max.c']
['/home/dangrahn/srciror/Demo/../llvm-build/Release+Asserts/bin/clang', '-O0', '-o', 'max', '/home/dangrahn/srciror/Demo/max.c']

mv: cannot stat ‘*.mut.*.c’: No such file or directory
```

I did set and verify my environment variables using the script. I am able to run with the sample `max.c`. Right now, I don't need to run tests, I just need to generate and verify some mutants.

Thanks!

## OS Info
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
CPE_NAME="cpe:/o:centos:centos:7"
```

**Comment by august782** [comment]
Hi,

From the log that you provided, it seems like somehow the paths are not set correctly, i.e., instead of all commands starting with "/srciror/Demo/", they should start with "$(pwd)/srciror/Demo/", where $(pwd) is the current directory. Are you running the commands within the Demo/ directory? Currently those scripts assume everything is run within that directory. Can you also output what the environment variable values are, e.g., what is the output of "echo ${SRCIROR_SRC_MUTATOR}"?

**Comment by dgrahn** [comment]
@august782 I apologize. I deidentified my paths by replacing `$(pwd)/srciror` with `/srciror`. I should have stated that. It's currently running at `~/srciror/Demo`. I'm running from that directory.

```
SRCIROR_LLVMMutate_LIB="~/srciror/Demo/../llvm-build/Release+Asserts/lib/LLVMMutate.so"
SRCIROR_LLVM_BIN="~/srciror/Demo/../llvm-build/Release+Asserts/bin/"
SRCIROR_LLVM_INCLUDES="~/srciror/Demo/../llvm-build/Release+Asserts/lib/clang/3.8.0/include/"
SRCIROR_SRC_MUTATOR="~/srciror/Demo/../SRCMutation/build/mutator"
```

**Comment by dgrahn** [comment]
@august782 I updated the paths to be correct and deidentified.

**Comment by august782** [comment]
Just to clarify, when you run the commands does it output the "\~" or does it output the full absolute path? If it outputs the "\~", I wonder if there is an issue with how it interprets the "\~".

**Comment by dgrahn** [comment]
You know what. I guess it really doesn't matter in this case. I have updated with the exact output.

**Comment by august782** [comment]
I'm honestly not sure what might be going on now, because after I swap out the code in max.c with the code in the initial post I was able to get generated mutants on my end. Can you run just the command after "THE ACTUAL COMMAND IS:"? Does it print out any errors?

Another thing to consider is that the demo script hardcodes some coverage lines and only makes mutants that mutates those lines. If you want to mutate everything, comment out the line in run-src-mutants.sh that writes into "~/.srciror/coverage" and delete/empty that file before running.

**Comment by dgrahn** [comment]
I'll try this first thing in the morning.

- Pardon my brevity. I sent this from my phone.

**Comment by dgrahn** [comment]
@august782 It was the coverage which was failing. Thank you so much for your help debugging!
